# Uncomment the next line to define  global platform for your project
# platform :ios, ‘8.0’

source 'https://github.com/CocoaPods/Specs.git'
source 'http://git.solot.co:10080/liuhuanqing/HQSpec.git'

use_frameworks!

target 'HQLocationManagerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HQLocationManagerDemo
  pod 'AFNetworking', '~>3.0' 
  pod 'HQDBDecode', :git => 'ssh://git@git.solot.co:10022/liuhuanqing/HQDBDecode.git'

end
