# Uncomment the next line to define  global platform for your project
# platform :ios, ‘8.0’

target 'HQLocationManagerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HQLocationManagerDemo
  pod 'AFNetworking', '~>3.0' 

end
